update non street classes
Bjorn248/scca_classifier pull request #100
Opened 2020-10-06 18:38 UTC by ZenVega

2020-10-07 05:18 UTC, Bjorn248 requested changes
Should be ready to merge after some adjustments

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['cs'],
Remove `all` here. Try not to have `all` and specific years.

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['hs'],
Remove `all`

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['hs'],
Remove `all`

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['hs'],
Remove `all`

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['gs'],
Remove `all`

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['stu'],
Remove `all` here and just make sure that every specific year has `stu` listed.

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['es'],
Remove `all` and make sure that every year has `es`

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['es'],
Remove `all`, make sure every year has `es`

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +      'all': ['hs'],
Remove `all`

2020-10-07 05:18 UTC, Bjorn248 commented on common.js
> +
Remove empty line

2020-10-07 11:49 UTC, ZenVega commented on common.js
> +
ok, i think i got it

2020-10-07 14:30 UTC, Bjorn248 requested changes
Found a syntax error

2020-10-08 13:43 UTC, Bjorn248 commented
@ZenVega would it be possible for you to rebase off of master and resolve the merge conflicts? Or perhaps just copy your toyota block and paste it into the file after you've pulled the latest code? Thanks.

2020-10-08 15:06 UTC, ZenVega commented
@Bjorn248  hey sorry, I don't really get what u mean. why did this conflict happen anyway? do you mean I shall make a PR with the non-Master branch?

2020-10-08 17:37 UTC, Bjorn248 commented
@ZenVega This conflict happened because the upstream code (the code hosted on github) was updated after you initially cloned it. You will either have to locally resolve the merge conflicts by doing a `git fetch` and `git pull`, or by cloning the repo again and pasting your changes into a more updated version of the repo. I think doing the former is a good exercise in learning git. Let me know if you need any more guidance, I can try to point you in the right direction.

2020-10-08 18:23 UTC, ZenVega commented
hmm... no, it seems I'm not getting it. so I git fetch the original(your repo)?
then git pull. (then it says everything is up to date) and pushing again doesn't seem to solve the problem

2020-10-08 21:35 UTC, Bjorn248 commented
@ZenVega try following this guide https://www.youtube.com/watch?v=__cR7uPBOIk. Let me know if this works out 😃

2020-10-09 09:20 UTC, ZenVega commented
oh man, I messed up my repository big time so I decided to solve it here in the commit.

2020-10-09 13:25 UTC, Bjorn248 commented
You're deleting the rest of the files in the repository, so I definitely cannot merge this. If you want to you can try copying your object to a local file, deleting your local copy of the repository, deleting your fork on github, reforking, cloning it from github again, and pasting your new object in and then opening a new PR? Kind of the "nuke it" option but it might be the easiest way to get to the finish line from here.

2020-10-09 13:25 UTC, closed without merging