add toyota into common.js
Bjorn248/scca_classifier pull request #120
Opened 2020-10-09 17:42 UTC by ZenVega

another try. I nuked everything down. man, this started out so chill, and then I created a monster.
I believe it should work now. thanks for the patience. and if u would add a hacktoberfest label I would appreciate it.
by the way, I had to install git-lfs. Don't know if that was on purpose

2020-10-09 18:00 UTC, Bjorn248 requested changes
Seems like there's an empty model here. I will consolidate a lot of the duplicate models you have listed here, so don't worry about that.

2020-10-10 10:54 UTC, ZenVega commented on common.js
> +    'Corolla (1600 & 1800,RWD)': {
ah, nope. that one got lost

2020-10-11 16:12 UTC, merged

2020-10-11 16:13 UTC, Bjorn248 commented
Thanks!

2020-10-12 08:54 UTC, ZenVega commented
man, thanks for the patience. good luck with your app