Add all Mercury vehicles to common.js #47
Bjorn248/scca_classifier pull request #140
Opened 2020-10-25 05:08 UTC by hasalassh

Add all Mercury vehicles to common.js #47

2020-10-25 07:14 UTC, Bjorn248 requested changes
Found a few models that are not Mercury. Please check all makes to make sure they are actually Mercury, and not Ford or another make.

2020-10-25 07:14 UTC, Bjorn248 commented on common.js
> +    'Maverick & Comet (6-cyl & 8cyl)': {
This seems like a syntax error. A model shouldn't be inside a model.

2020-10-25 07:14 UTC, Bjorn248 commented on common.js
> +      'Thunderbird (V6 & TurboCoupe)': {
This is not a Mercury.

2020-10-25 07:14 UTC, Bjorn248 commented on common.js
> +    'Maverick & Comet (6-cyl & 8cyl)': {
The Maverick is not a Mercury model, but the Comet is

2020-10-25 17:47 UTC, hasalassh commented
@Bjorn248 Thanks for the review comments. I have done the requested modifications...!

2020-10-26 01:22 UTC, hasalassh commented
> Found a few models that are not Mercury. Please check all makes to make sure they are actually Mercury, and not Ford or another make.

Removed few models that are not Mercury from the json...!

2020-10-26 13:15 UTC, merged

2020-10-26 13:15 UTC, Bjorn248 commented
Thanks

2020-10-26 14:40 UTC, hasalassh commented
@Bjorn248 Thanks for the support...!