Added Scion vehicles
Bjorn248/scca_classifier pull request #80
Opened 2020-10-06 03:58 UTC by dmchale

Addresses #24 

Only model I could not find an example to follow from other makes was for the base iQ, since it is defined as "Excluded from Street Category for reasons of stability per Section 3.1" on pg 183. Let me know if it should be addressed in a specific way; I left it out for now.

2020-10-06 04:07 UTC, Bjorn248 requested changes
Looks good, would just like to merge the models a bit. Thanks!

2020-10-06 04:07 UTC, Bjorn248 commented on common.js
> +    'tC (incl. Release Series 5.0 2009)': {
This should probably be merged with the regular `tC` model, just by adding `hs` to the classes array for `tC` and deleting this one.

2020-10-06 04:07 UTC, Bjorn248 commented on common.js
> +      'all': ['cs'],
Please add an entry for each year (2013-2016) and also be sure to add `ssc` as a valid class.

2020-10-06 04:07 UTC, Bjorn248 commented on common.js
> +      'all': ['ds'],
Please add an entry for each year (2013-2016) and also be sure to add `ssc` as a valid class.

2020-10-06 04:07 UTC, Bjorn248 commented on common.js
> +    'FR-S *Limited Prep*': {
You can remove this for now, I haven't figured out a great way to incorporate limited prep into the website yet.

2020-10-06 04:07 UTC, Bjorn248 commented on common.js
> +    'FR-S (incl. Release Series 1.0 and 2.0)': {
This can be merged with the TRD and non-TRD FR-S models below. So basically, just add `stx` and `csp` to all of their class arrays.

2020-10-06 04:13 UTC, Bjorn248 requested changes
Also, could you add the year ranges specified in the rules? Thanks!

2020-10-06 04:13 UTC, Bjorn248 commented on common.js
> +      'all': ['sts','fsp'],
Please add the year range specified in the rules (2005-2016)

2020-10-06 04:13 UTC, Bjorn248 commented on common.js
> +      'all': ['hs','sts'],
Please add the year range specified in the rules (2004-2006)

2020-10-06 04:13 UTC, Bjorn248 commented on common.js
> +      'all': ['hs','sts'],
Please add the year range specified in the rules (2008-2015)

2020-10-06 04:13 UTC, Bjorn248 commented on common.js
> +      'all': ['hs','sts'],
Please make this 2016 instead of all

2020-10-06 04:13 UTC, Bjorn248 commented on common.js
> +      'all': ['hs','sts'],
Please make this 2016 instead of all

2020-10-06 04:13 UTC, Bjorn248 commented on common.js
> +      'all': ['sts'],
Please add the year range specified in the rules (2008-2013)

2020-10-07 02:11 UTC, dmchale commented
Made some updates per your requests, @Bjorn248 .... see https://github.com/Bjorn248/scca_classifier/pull/80/commits/2c742bdebf3725abc89a9a28a736eaacc5f59c81

2020-10-07 02:32 UTC, merged

2020-10-07 02:32 UTC, Bjorn248 commented
Thanks!

2020-10-07 02:37 UTC, dmchale commented
Happy to help!