Add all Saab vehicles to common.js
Bjorn248/scca_classifier pull request #88
Opened 2020-10-06 12:07 UTC by dinukad

resolve #34

2020-10-06 22:33 UTC, Bjorn248 requested changes
This one seems to be a bit tricky. If you'd like me to make a separate branch for you to submit your PR to then I can merge the classes there, or if you want to try to fix it yourself you are welcome to. Ideally, we'd want to have as few model definitions as we need. Also, we'll have to look up each model to see if it is a turbo (so then it goes into `gs`) or a non-turbo (so then it goes into `hs`)

2020-10-06 22:33 UTC, Bjorn248 commented on common.js
> +    '900 Turbo': {
You shouldn't have duplicate keys. You have `900 Turbo` twice. Please merge these two, by adding `fp` to all years or by removing this model and adding `fsp` to the model with `all` for the years.

2020-10-06 22:33 UTC, Bjorn248 commented on common.js
> +    '99': {
Resolve duplicate keys, you have `99` twice.

2020-10-06 22:33 UTC, Bjorn248 commented on common.js
> +      'all': ['dsp']
Can add `gs` here since you know all turbo models are eligible for that class.

2020-10-06 22:33 UTC, Bjorn248 commented on common.js
> +    '900 Turbo': {
Can add `gs` here since you know all turbo models are eligble for that class.

2020-10-07 03:18 UTC, dinukad commented
@Bjorn248 Added changes as requested. Please review.

2020-10-07 05:10 UTC, merged

2020-10-07 05:10 UTC, Bjorn248 commented
Thanks!