Added Lancia object and car models to common.js file
Bjorn248/scca_classifier pull request #94
Opened 2020-10-06 13:52 UTC by hauze-v

2020-10-06 14:40 UTC, Bjorn248 requested changes
Some class correction and model merging.

2020-10-06 14:40 UTC, Bjorn248 commented on common.js
> +      'all': ['hs', 'bsp']
This is in `csp`

2020-10-06 14:40 UTC, Bjorn248 commented on common.js
> +      '1976': ['dp']
This should be merged with the above `Scorpion`. There was only one kind of Scorpion sold in North America, and it had the 1756 cc engine. Just add `dp` to the existing `Scorpion` and you should be good!

2020-10-07 11:55 UTC, hauze-v commented
Thanks for your feedback. Please check if it's okay now.

2020-10-07 14:31 UTC, merged

2020-10-07 14:31 UTC, Bjorn248 commented
Thanks!